name: Test Project
on: push
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: NPM Install
        run: npm ci
      - name: Run tests
        run: npm run test
